# Variables
@baseUrl = http://localhost:3333
@token = {{auth.response.body.$.token}}
@projectId = {{createProject.response.body.$.projectId}}

###

# @name auth
POST {{baseUrl}}/sessions/github
Content-Type: application/json

{
  "code": "e60b8fd1e924a0d1e067"
}

###

# @name getProfile
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}

###

# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Project 1",
  "description": "project description",
  "type": "fullstack",
  "githubUrl": "https://github.com/sercomp"
}

###

# @name findProjectsByUserId
GET {{baseUrl}}/projects
Authorization: Bearer {{token}}

###

# @name findProjectById
GET {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}

###

# @name updateProject
PUT {{baseUrl}}/projects/{{projectId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Project updated",
  "description": "project description updated",
  "type": "backend",
  "githubUrl": "https://github.com/project-updated"
}

###

# @name deleteProject
DELETE {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}