# Variables
@baseUrl = http://localhost:3333
@token = {{auth.response.body.$.token}}
@projectId = {{createProject.response.body.$.projectId}}

###

# @name auth
POST {{baseUrl}}/sessions/github
Content-Type: application/json

{
  "code": "c1a689397888c7cf3be0"
}

###

# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Project 1",
  "description": "project description",
  "type": "fullstack",
  "githubUrl": "https://github.com/project1"
}